-- MySQL Script generated by MySQL Workbench
-- 05/14/17 00:30:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `tipo` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_usuario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`datos_personales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_personales` (
  `id_datospersonales` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido_paterno` VARCHAR(45) NULL COMMENT '',
  `apellido_materno` VARCHAR(45) NULL COMMENT '',
  `fecha_nacimiento` DATE NULL COMMENT '',
  `genero` VARCHAR(45) NULL COMMENT '',
  `telefono` VARCHAR(45) NULL COMMENT '',
  `celular` VARCHAR(45) NULL COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_datospersonales`)  COMMENT '',
  INDEX `fk_usuario_datospersonale_idx` (`id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_datospersonale`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`datos_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_cliente` (
  `id_datoscliente` INT NOT NULL COMMENT '',
  `curp` VARCHAR(45) NULL COMMENT '',
  `rfc` VARCHAR(45) NULL COMMENT '',
  `sueldo` FLOAT NULL COMMENT '',
  `imagen` VARCHAR(45) NULL COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_datoscliente`)  COMMENT '',
  INDEX `fk_datoscliente_usuarios_idx` (`id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_datoscliente_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `idproductos` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(150) NULL COMMENT '',
  `precio_venta` FLOAT NULL COMMENT '',
  `precio_compra` VARCHAR(45) NULL COMMENT '',
  `cantidad` INT NULL COMMENT '',
  `imagen` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idproductos`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flete` (
  `id_flete` INT NOT NULL COMMENT '',
  `placa` VARCHAR(45) NULL COMMENT '',
  `marca` VARCHAR(45) NULL COMMENT '',
  `modelo` VARCHAR(45) NULL COMMENT '',
  `color` VARCHAR(45) NULL COMMENT '',
  `costo` FLOAT NULL COMMENT '',
  PRIMARY KEY (`id_flete`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `idventa` INT NOT NULL COMMENT '',
  `idusuario` INT NOT NULL COMMENT '',
  `idflete` INT NOT NULL COMMENT '',
  `id_vendedor` INT NOT NULL COMMENT '',
  `id_chofer` INT NOT NULL COMMENT '',
  `domicilio` VARCHAR(100) NULL COMMENT '',
  `fecha_venta` DATE NULL COMMENT '',
  `total` FLOAT NOT NULL COMMENT '',
  PRIMARY KEY (`idventa`)  COMMENT '',
  INDEX `fk_venta_flete_idx` (`idflete` ASC)  COMMENT '',
  INDEX `fk_venta_usuario_idx` (`idusuario` ASC)  COMMENT '',
  INDEX `fk_venta_vendedor_idx` (`id_vendedor` ASC)  COMMENT '',
  INDEX `fk_venta_chofer_idx` (`id_chofer` ASC)  COMMENT '',
  CONSTRAINT `fk_venta_flete`
    FOREIGN KEY (`idflete`)
    REFERENCES `mydb`.`flete` (`id_flete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_cliente`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_vendedor`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_chofer`
    FOREIGN KEY (`id_chofer`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_venta` (
  `id_detalleventa` INT NOT NULL COMMENT '',
  `id_venta` INT NOT NULL COMMENT '',
  `id_producto` INT NOT NULL COMMENT '',
  `cantidad` INT NULL COMMENT '',
  `subtotal` FLOAT NULL COMMENT '',
  PRIMARY KEY (`id_detalleventa`)  COMMENT '',
  INDEX `fk_detalleventa_venta_idx` (`id_venta` ASC)  COMMENT '',
  INDEX `fk_detalleventa_producto_idx` (`id_producto` ASC)  COMMENT '',
  CONSTRAINT `fk_detalleventa_venta`
    FOREIGN KEY (`id_venta`)
    REFERENCES `mydb`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleventa_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`renta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`renta` (
  `idrenta` INT NOT NULL COMMENT '',
  `id_flete` INT NOT NULL COMMENT '',
  `id_cliente` INT NOT NULL COMMENT '',
  `id_vendedor` INT NOT NULL COMMENT '',
  `id_chofer` INT NOT NULL COMMENT '',
  `fecha_entrega` DATE NULL COMMENT '',
  `fecha_devolucion` DATE NULL COMMENT '',
  `domicilio` VARCHAR(100) NULL COMMENT '',
  `total` FLOAT NULL COMMENT '',
  PRIMARY KEY (`idrenta`)  COMMENT '',
  INDEX `fk_renta_cliente_idx` (`id_cliente` ASC)  COMMENT '',
  INDEX `fk_renta_vendedor_idx` (`id_vendedor` ASC)  COMMENT '',
  INDEX `fk_renta_chofer_idx` (`id_chofer` ASC)  COMMENT '',
  INDEX `fk_renta_flete_idx` (`id_flete` ASC)  COMMENT '',
  CONSTRAINT `fk_renta_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_renta_vendedor`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_renta_chofer`
    FOREIGN KEY (`id_chofer`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_renta_flete`
    FOREIGN KEY (`id_flete`)
    REFERENCES `mydb`.`flete` (`id_flete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_renta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_renta` (
  `id_detallerenta` INT NOT NULL COMMENT '',
  `id_renta` INT NOT NULL COMMENT '',
  `id_producto` INT NOT NULL COMMENT '',
  `cantidad` INT NULL COMMENT '',
  `subtotal` DATE NULL COMMENT '',
  PRIMARY KEY (`id_detallerenta`)  COMMENT '',
  INDEX `fk_detallerenta_venta_idx` (`id_renta` ASC)  COMMENT '',
  INDEX `fk_detallerenta_producto_idx` (`id_producto` ASC)  COMMENT '',
  CONSTRAINT `fk_detallerenta_venta`
    FOREIGN KEY (`id_renta`)
    REFERENCES `mydb`.`renta` (`idrenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallerenta_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`credito_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`credito_cliente` (
  `idcredito_cliente` INT NOT NULL COMMENT '',
  `id_cliente` INT NOT NULL COMMENT '',
  `sueldo` FLOAT NULL COMMENT '',
  `credito` FLOAT NULL COMMENT '',
  PRIMARY KEY (`idcredito_cliente`)  COMMENT '',
  INDEX `fk_creditocliente_cliente_idx` (`id_cliente` ASC)  COMMENT '',
  CONSTRAINT `fk_creditocliente_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deuda_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deuda_cliente` (
  `id_deudacliente` INT NOT NULL COMMENT '',
  `id_cliente` INT NOT NULL COMMENT '',
  `pago_quincenal` FLOAT NULL COMMENT '',
  `deuda_total` FLOAT NULL COMMENT '',
  PRIMARY KEY (`id_deudacliente`)  COMMENT '',
  INDEX `fk_deuda_cliente_idx` (`id_cliente` ASC)  COMMENT '',
  CONSTRAINT `fk_deuda_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
